name: defender

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: '8.0.3'
  camera: '^0.9.4+19'
  cloud_firestore: '^3.1.13'
  cupertino_icons: '^1.0.2'
  equatable: '^2.0.3'
  firebase_auth: '^3.3.14'
  firebase_core: '^1.14.1'
  firebase_crashlytics: '^2.6.3'
  firebase_storage: '^10.2.12'
  flow_builder: '^0.0.6'
  flutter_bloc: '^8.0.1'
  formz: '^0.4.1'
  google_sign_in: '^5.3.0'
  hydrated_bloc: '^8.1.0'
  intl: '^0.17.0'
  json_annotation: '^4.4.0'
  meta: '^1.3.0'
  path_provider: '^2.0.9'
  permission_handler: '^9.2.0'
  rxdart: '^0.27.3'
  uuid: '^3.0.4'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: '^1.0.0'
  build_runner: '^2.0.0'
  json_serializable: '^6.0.0'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logos/
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf